// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxErloOFAv6bJfDHeR2zM4Ng8hdcNUvtU',
    appId: '1:339007831230:web:beb3002bb35738a6b5f2ef',
    messagingSenderId: '339007831230',
    projectId: 'simple-payment-f7477',
    authDomain: 'simple-payment-f7477.firebaseapp.com',
    storageBucket: 'simple-payment-f7477.firebasestorage.app',
    measurementId: 'G-7WBTBHSQR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-KYesRsmrXWgmwk8XpLmzzxaqMf46K84',
    appId: '1:339007831230:android:43e59cd6287535dab5f2ef',
    messagingSenderId: '339007831230',
    projectId: 'simple-payment-f7477',
    storageBucket: 'simple-payment-f7477.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUnGFqsdHdsyKiVov9yalpMKj5OsTRhfA',
    appId: '1:339007831230:ios:e5cc0d571e870a81b5f2ef',
    messagingSenderId: '339007831230',
    projectId: 'simple-payment-f7477',
    storageBucket: 'simple-payment-f7477.firebasestorage.app',
    iosBundleId: 'com.example.simplepaymentcard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUnGFqsdHdsyKiVov9yalpMKj5OsTRhfA',
    appId: '1:339007831230:ios:e5cc0d571e870a81b5f2ef',
    messagingSenderId: '339007831230',
    projectId: 'simple-payment-f7477',
    storageBucket: 'simple-payment-f7477.firebasestorage.app',
    iosBundleId: 'com.example.simplepaymentcard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxErloOFAv6bJfDHeR2zM4Ng8hdcNUvtU',
    appId: '1:339007831230:web:9aed02e3b123fce3b5f2ef',
    messagingSenderId: '339007831230',
    projectId: 'simple-payment-f7477',
    authDomain: 'simple-payment-f7477.firebaseapp.com',
    storageBucket: 'simple-payment-f7477.firebasestorage.app',
    measurementId: 'G-CGDGYSXX2T',
  );
}
